{
  description = "Stellar CLI - Starship theme manager";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Derived, never hand-maintained: this builds the working tree, which
        # is not a release, so pinning a release number here would only ever go
        # stale. nix/package.nix carries the real version for the release
        # build - see scripts/release.sh, which bumps it.
        commit = self.rev or self.dirtyRev or "unknown";
        version = "dev-${builtins.substring 0 7 commit}";
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            # nix develop drops into this bash; the default stdenv one has no
            # readline, which breaks interactive prompts (literal \[ \] from
            # starship) and completion (`shopt: progcomp: invalid shell option`).
            bashInteractive

            go

            # Go development tools
            gopls
            gotools
            go-tools
            golangci-lint

            # For test runner JSON parsing
            jq
          ];

          shellHook = ''
            # stdenv points SHELL at its readline-less bash; anything spawning
            # $SHELL (e.g. `stellar preview`) should get the interactive one.
            export SHELL="${pkgs.bashInteractive}/bin/bash"
            export GOPATH="$HOME/go"
            export PATH="$GOPATH/bin:$PATH"
            export GOPROXY="https://proxy.golang.org,direct"
            export GOSUMDB="sum.golang.org"

            echo "✳ Stellar CLI development environment loaded!"
          '';
        };

        # Builds the working tree, so `nix build` / `nix run` exercise whatever
        # you currently have checked out. nix/package.nix is the release build
        # of the same program, pinned to a tag, and is the file to upstream to
        # nixpkgs.
        packages.default = pkgs.buildGoModule {
          pname = "stellar";
          inherit version;

          src = ./.;

          vendorHash = "sha256-CKoFZc7S5za0jZ/LA0abZ7AA/Q7+MtdW9NZznCEzap0=";

          # Deliberately no -X main.version: this builds whatever is checked
          # out, which is not a release. Stamping a release version here would
          # make IsDev() false, so every `nix build` / `nix run` from a working
          # tree would send a real install report to the hub tagged as that
          # version and start checking GitHub for updates. Leaving it at "dev"
          # keeps developer machines out of the telemetry.
          #
          # nix/package.nix is the release build and does stamp the version.
          ldflags = [
            "-s"
            "-w"
            "-X main.commit=${commit}"
          ];

          nativeBuildInputs = [ pkgs.installShellFiles ];

          preCheck = ''
            # The suite writes into ~/.config/stellar, and the sandbox HOME is
            # not writable.
            export HOME=$(mktemp -d)
            export STELLAR_NO_TELEMETRY=1
          '';

          # Completions are generated by running the binary, which only works
          # when the build machine can execute what was just built.
          postInstall = pkgs.lib.optionalString
            (pkgs.stdenv.buildPlatform.canExecute pkgs.stdenv.hostPlatform) ''
            # `stellar completion` runs the root PersistentPreRunE, which
            # creates ~/.config/stellar and starts the install report. Scratch
            # HOME so it cannot fail, and no telemetry from a build.
            export HOME=$(mktemp -d)
            export STELLAR_NO_TELEMETRY=1

            installShellCompletion --cmd stellar \
              --bash <($out/bin/stellar completion bash) \
              --fish <($out/bin/stellar completion fish) \
              --zsh <($out/bin/stellar completion zsh)
          '';

          meta = {
            description = "Discover, preview, and apply Starship prompt themes";
            homepage = "https://github.com/a3chron/stellar";
            license = pkgs.lib.licenses.mit;
            mainProgram = "stellar";
            platforms = pkgs.lib.platforms.unix ++ pkgs.lib.platforms.windows;
          };
        };

        # The release build, exactly as nixpkgs would build it. Handy for
        # checking the upstream expression still works before sending a PR.
        packages.release = pkgs.callPackage ./nix/package.nix { };
      }
    );
}
