Output demo.gif

Set FontSize 18
Set Width 1200
Set Height 800
Set Shell "bash"
Set TypingSpeed 80ms

Type "bash -i"
Enter
Sleep 500ms

Type "./stellar apply a3chron/ctp-blue"
Enter
Sleep 2s

Type "clear"
Enter
Sleep 1s

Type "./stellar apply a3chron/ctp-green"
Enter
Sleep 3s

Type "./stellar rollback"
Enter
Sleep 3s

Type "./stellar list"
Enter
Sleep 3s

Type "./stellar remove a3chron/ctp-green"
Enter
Sleep 2s
